const choices = [
  // Easy (20)
  { text: "Taking the MRT instead of driving.", isGood: true, difficulty: "easy" },
  { text: "Using single-use plastic bags.", isGood: false, difficulty: "easy" },
  { text: "Recycling paper, plastic, and metal.", isGood: true, difficulty: "easy" },
  { text: "Leaving the tap running while brushing.", isGood: false, difficulty: "easy" },
  { text: "Bringing your own water bottle.", isGood: true, difficulty: "easy" },
  { text: "Driving alone to work every day.", isGood: false, difficulty: "easy" },
  { text: "Using LED light bulbs.", isGood: true, difficulty: "easy" },
  { text: "Taking long hot showers daily.", isGood: false, difficulty: "easy" },
  { text: "Eating more plant-based meals.", isGood: true, difficulty: "easy" },
  { text: "Forgetting to turn off lights.", isGood: false, difficulty: "easy" },
  { text: "Using reusable shopping bags.", isGood: true, difficulty: "easy" },
  { text: "Throwing batteries in regular trash.", isGood: false, difficulty: "easy" },
  { text: "Cycling instead of using a motorbike.", isGood: true, difficulty: "easy" },
  { text: "Printing documents unnecessarily.", isGood: false, difficulty: "easy" },
  { text: "Unplugging chargers when not in use.", isGood: true, difficulty: "easy" },
  { text: "Leaving your car engine idling.", isGood: false, difficulty: "easy" },
  { text: "Donating old clothes.", isGood: true, difficulty: "easy" },
  { text: "Using disposable cutlery for lunch.", isGood: false, difficulty: "easy" },
  { text: "Buying locally grown vegetables.", isGood: true, difficulty: "easy" },
  { text: "Throwing plastic bottles in general waste.", isGood: false, difficulty: "easy" },

  // Medium (18)
  { text: "Composting kitchen waste.", isGood: true, difficulty: "medium" },
  { text: "Flying domestically multiple times a month.", isGood: false, difficulty: "medium" },
  { text: "Using public transport during peak hours.", isGood: true, difficulty: "medium" },
  { text: "Regularly ordering fast fashion online.", isGood: false, difficulty: "medium" },
  { text: "Switching to a plant-based diet.", isGood: true, difficulty: "medium" },
  { text: "Buying water in plastic bottles daily.", isGood: false, difficulty: "medium" },
  { text: "Using a fan instead of aircon.", isGood: true, difficulty: "medium" },
  { text: "Leaving electronics in standby mode.", isGood: false, difficulty: "medium" },
  { text: "Taking the stairs instead of the elevator.", isGood: true, difficulty: "medium" },
  { text: "Regular use of ride-hailing apps.", isGood: false, difficulty: "medium" },
  { text: "Buying second-hand electronics.", isGood: true, difficulty: "medium" },
  { text: "Leaving air conditioning on when not home.", isGood: false, difficulty: "medium" },
  { text: "Choosing e-receipts over printed ones.", isGood: true, difficulty: "medium" },
  { text: "Burning waste in your backyard.", isGood: false, difficulty: "medium" },
  { text: "Installing water-saving taps.", isGood: true, difficulty: "medium" },
  { text: "Using wet wipes frequently.", isGood: false, difficulty: "medium" },
  { text: "Replacing meat with tofu or lentils.", isGood: true, difficulty: "medium" },
  { text: "Upgrading your phone yearly.", isGood: false, difficulty: "medium" },

  // Hard (12)
  { text: "Installing solar panels at home.", isGood: true, difficulty: "hard" },
  { text: "Owning multiple large vehicles.", isGood: false, difficulty: "hard" },
  { text: "Joining a community clean-up effort.", isGood: true, difficulty: "hard" },
  { text: "Living in a high-energy-consuming smart home.", isGood: false, difficulty: "hard" },
  { text: "Choosing a zero-waste lifestyle.", isGood: true, difficulty: "hard" },
  { text: "Flying business class frequently.", isGood: false, difficulty: "hard" },
  { text: "Supporting sustainable fashion brands.", isGood: true, difficulty: "hard" },
  { text: "Using peat-based soil for gardening.", isGood: false, difficulty: "hard" },
  { text: "Living without owning a car.", isGood: true, difficulty: "hard" },
  { text: "Washing clothes daily with hot water.", isGood: false, difficulty: "hard" },
  { text: "Building with eco-friendly materials.", isGood: true, difficulty: "hard" },
  { text: "Ignoring recycling laws and fines.", isGood: false, difficulty: "hard" },
];

export default choices;
